#!/bin/sh

# Stop tiny-dfr during suspend so it releases the Touch Bar DRM device. Do not
# force USB recovery here; resetting the T2 Touch Bar device can stall/repeat the
# internal keyboard/trackpad on some machines.

case "$1" in
    pre)
        systemctl stop tiny-dfr.service
        ;;
    post)
        # Give apple-bce/appletbdrm a moment to re-enumerate after resume.
        sleep 2
        systemctl start tiny-dfr.service
        ;;
esac
